# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tepid Wanderer"
subtitle: "See the world through my eyes!"
author: "Tepid Wanderer"
header:
 title: "Photography"
 subtitle: "by Tepid Wanderer"
footer:
 name: "Hey there, my name is Ash"
 bio: "I am a photographer experimenting with both visible light and invisible light photography."
# github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
#web_design: "AJ"
social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/tepidwanderer"
#  dribbble: "https://dribbble.com/rampatra"
#  linkedin: "https://in.linkedin.com/in/ram-patra"
#  github: "https://www.github.com/rampatra"
